/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal.controladores;

import java.awt.Dialog;
import javax.swing.JDialog;
import productos.vistas.VentanaAMProducto;
import usuarios.vistas.VentanaAMUsuario;

/**
 *
 * @author ulise
 */
public class VentanaHome extends JDialog {

    /**
     * Creates new form VentanaHome
     */
    public VentanaHome(Dialog ventanaPadre) {
        super(ventanaPadre, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BIENVENIDO = new javax.swing.JLabel();
        PROD = new javax.swing.JButton();
        USU = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BIENVENIDO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BIENVENIDO.setForeground(new java.awt.Color(255, 255, 255));
        BIENVENIDO.setText("Bienvenido");
        BIENVENIDO.setToolTipText("");
        BIENVENIDO.setMaximumSize(new java.awt.Dimension(159, 116));
        BIENVENIDO.setMinimumSize(new java.awt.Dimension(159, 116));
        getContentPane().add(BIENVENIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 36, -1, -1));

        PROD.setText("Productos");
        PROD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODActionPerformed(evt);
            }
        });
        getContentPane().add(PROD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 124, 165, 108));

        USU.setText("Usuarios");
        USU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUActionPerformed(evt);
            }
        });
        getContentPane().add(USU, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 124, 164, 108));

        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 244, 341, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/controladores/FondoVentanaHome(NoTocar).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODActionPerformed
        VentanaAMProducto ventana = new VentanaAMProducto(null);
        ventana.setLocationRelativeTo(null);
        ventana.setTitle("Nuevo Producto");
        this.dispose();
        ventana.setVisible(true);

    }//GEN-LAST:event_PRODActionPerformed

    private void USUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUActionPerformed
        VentanaAMUsuario ventana = new VentanaAMUsuario(null);
        ventana.setLocationRelativeTo(null);
        ventana.setTitle("Nuevo Usuario");
        this.dispose();
        ventana.setVisible(true);

    }//GEN-LAST:event_USUActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaHome dialog = new VentanaHome(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIENVENIDO;
    private javax.swing.JButton PROD;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton USU;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
